package es.iessaladillo.pedrojoya.pr081.modelos;

// Class generated by Clever Models 

public class City {
    private Integer id;
    private String name;
    private Coord coord;
    private String country;
    private Integer population;

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Coord getCoord() {
        return coord;
    }

    public String getCountry() {
        return country;
    }

    public Integer getPopulation() {
        return population;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCoord(Coord coord) {
        this.coord = coord;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public void setPopulation(Integer population) {
        this.population = population;
    }
}