package es.iessaladillo.pedrojoya.pr081.modelos;

// Class generated by Clever Models 

public class Coord {
    private Float lon;
    private Float lat;

    public Float getLon() {
        return lon;
    }

    public Float getLat() {
        return lat;
    }

    public void setLon(Float lon) {
        this.lon = lon;
    }

    public void setLat(Float lat) {
        this.lat = lat;
    }
}