package es.iessaladillo.pedrojoya.pr081.modelos;

// Class generated by Clever Models 

public class Temp {
    private Float day;
    private Float min;
    private Float max;
    private Float night;
    private Float eve;
    private Float morn;

    public Float getDay() {
        return day;
    }

    public Float getMin() {
        return min;
    }

    public Float getMax() {
        return max;
    }

    public Float getNight() {
        return night;
    }

    public Float getEve() {
        return eve;
    }

    public Float getMorn() {
        return morn;
    }

    public void setDay(Float day) {
        this.day = day;
    }

    public void setMin(Float min) {
        this.min = min;
    }

    public void setMax(Float max) {
        this.max = max;
    }

    public void setNight(Float night) {
        this.night = night;
    }

    public void setEve(Float eve) {
        this.eve = eve;
    }

    public void setMorn(Float morn) {
        this.morn = morn;
    }
}